# This file contains configuration for pytest.
[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
addopts = --cov-context=test -m "not live"
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    e2e: marks tests as end-to-end
    live: marks tests as live (requires network)
