# This file defines the configuration for each agent in the pForge system.
# The keys are the agent names, and the values are their configurations.
agents:
  observer:
    enabled: true
    spawn_weight: 1.0
    spawn_threshold: 0.20
    retire_threshold: -0.10
    max_concurrency: 1

  spec_oracle:
    enabled: true
    spawn_weight: 0.8
    spawn_threshold: 0.15
    retire_threshold: -0.05
    max_concurrency: 1

  predictor:
    enabled: true
    spawn_weight: 0.9
    spawn_threshold: 0.18
    retire_threshold: -0.08
    max_concurrency: 1

  planner:
    enabled: true
    spawn_weight: 1.2
    spawn_threshold: 0.10
    retire_threshold: -0.05
    max_concurrency: 1

  fixer:
    enabled: true
    spawn_weight: 1.4
    spawn_threshold: 0.25
    retire_threshold: 0.02
    max_concurrency: 2

  misfit:
    enabled: true
    spawn_weight: 1.1
    spawn_threshold: 0.12
    retire_threshold: -0.03
    max_concurrency: 1

  false_piece:
    enabled: true
    spawn_weight: 0.7
    spawn_threshold: 0.08
    retire_threshold: -0.02
    max_concurrency: 1

  backtracker:
    enabled: true
    spawn_weight: 0.6
    spawn_threshold: 0.05
    retire_threshold: -0.01
    max_concurrency: 1

  conflict_detector:
    enabled: true
    spawn_weight: 0.4
    spawn_threshold: 0.07
    retire_threshold: -0.02
    max_concurrency: 1

  efficiency_analyst:
    enabled: true
    spawn_weight: 0.3
    spawn_threshold: 0.0
    retire_threshold: 0.0
    max_concurrency: 1

  intent_router:
    enabled: true
    spawn_weight: 0.4
    spawn_threshold: 0.0
    retire_threshold: 0.0
    max_concurrency: 1

  recovery:
    enabled: true
    spawn_weight: 1.5
    spawn_threshold: 0.3
    retire_threshold: 0.0
    max_concurrency: 1

  self_repair:
    enabled: true
    spawn_weight: 0.5
    spawn_threshold: 0.1
    retire_threshold: -0.1
    max_concurrency: 1

  summarizer:
    enabled: true
    spawn_weight: 0.5
    spawn_threshold: 0.1
    retire_threshold: -0.1
    max_concurrency: 1
