global:
  scrape_interval: 15s
scrape_configs:
  - job_name: pforge
    metrics_path: /metrics
    static_configs:
      - targets: ['pforge.pforge.svc.cluster.local']
  - job_name: redis
    static_configs:
      - targets: ['redis:6379']
